### ISSUE TITLE
Clarification of documentation on alias-and-virtual-networks

### ISSUE THREAD

**Issue by paul-hammant** [DtxdF/AppJail.docs#1]
Re file https://github.com/DtxdF/AppJail.docs/blob/main/docs/networking/virtual-networks/alias-and-virtual-networks.md

```
To use both options we need to create another loopback interface:

sysrc cloned_interfaces+="lo1"
sysrc ifconfig_lo1_name="appjail0"
service netif cloneup

The interface name can be whatever you want, but I recommend keeping it simple.

appjail quick debian \
    alias="appjail0" \
    virtualnet="development" \
    osversion=bullseye \
    type=linux+debootstrap \
    start \
    linuxfs \
    devfs_ruleset=0 \
    template=/tmp/linux.conf \
    overwrite
```

The three lines `sysrc, sysrc and service` appear to be key to getting multiple of of the AppJail-makejails examples going. I'm still leaning this stuff, so I'll discover shortly whether I need to make these unique per jailed thing I'm making. I mean appjail1, appjail2, appjail3 and so on, whether one appjail0 will cover all the jailed things I'll be experimenting with.

Really though, I'm posting this issue because I do not under understand the significance of  `appjail quick debian ...` in this page.  Does it relate to the English line above it `The interface name can be whatever you want, but I recommend keeping it simple`? It does not appear to follow.  The https://github.com/AppJail-makejails/alpine-linux example links to this page. I've executed the three lines `sysrc, sysrc and service` then rerun the makejail of the example and it works. Thus I am not sure of the significance of the `appjail quick debian ...` script in this documentation page.

**Comment by DtxdF** [comment]
You don't need to create different interfaces for each jail, even if you plan to use LinuxJails only. Aliasing and Virtual Networks are more relevant for LinuxJails, that's why the documentation explains this example, but you can perfectly use alising and virtual networks for any other jail type.

I recommend you read `appjail help quick` to familiarize yourself with the syntax, examples and more explanations. I know a manual page is much better, so I am working on it:

https://github.com/DtxdF/AppJail?tab=readme-ov-file#todo

In fact, the official documentation will probably be a handbook or a big tutorial and the man page will explain everything in more detail.

But basically `appjail quick debian ...`:

* `appjail`: command.
* `quick`: subcommand.
* `debian`: jail name.

After the jail name you must specify the relevant options only for `appjail quick`.

**Comment by DtxdF** [comment]
This issue has been closed due to inactivity. You can reopen it if you wish.
